/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'service-categories': ServiceCategory;
    services: Service;
    'service-addons': ServiceAddon;
    'service-areas': ServiceArea;
    'time-slots': TimeSlot;
    'disabled-dates': DisabledDate;
    beauticians: Beautician;
    addresses: Address;
    appointments: Appointment;
    coupons: Coupon;
    offers: Offer;
    reviews: Review;
    'before-after': BeforeAfter;
    reels: Reel;
    faqs: Faq;
    pages: Page;
    notifications: Notification;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'service-categories': ServiceCategoriesSelect<false> | ServiceCategoriesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'service-addons': ServiceAddonsSelect<false> | ServiceAddonsSelect<true>;
    'service-areas': ServiceAreasSelect<false> | ServiceAreasSelect<true>;
    'time-slots': TimeSlotsSelect<false> | TimeSlotsSelect<true>;
    'disabled-dates': DisabledDatesSelect<false> | DisabledDatesSelect<true>;
    beauticians: BeauticiansSelect<false> | BeauticiansSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    appointments: AppointmentsSelect<false> | AppointmentsSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'before-after': BeforeAfterSelect<false> | BeforeAfterSelect<true>;
    reels: ReelsSelect<false> | ReelsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    homepage: Homepage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Payload CMS login is for admins only. Create the first Super Admin, then sign in.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role: 'super-admin' | 'manager' | 'content-manager' | 'beautician' | 'customer';
  phone?: string | null;
  whatsapp?: string | null;
  /**
   * Upload a new file into Media, or choose one already saved there.
   */
  photo?: (string | null) | Media;
  accountStatus?: ('active' | 'suspended' | 'pending') | null;
  favouriteServices?: (string | Service)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  password?: string | null;
  collection: 'users';
}
/**
 * All website photos, videos and icons are stored here. Upload once, then select the file on Homepage, Services, Beauticians, Reels, Offers and other pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Short text that describes this file on the website.
   */
  alt: string;
  /**
   * Optional folder so files are easier to find.
   */
  folder?:
    | ('general' | 'brand' | 'homepage' | 'services' | 'beauticians' | 'reels' | 'before-after' | 'offers' | 'reviews')
    | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  name: string;
  /**
   * Leave empty — it is created from the name.
   */
  slug: string;
  category: string | ServiceCategory;
  shortDescription: string;
  fullDescription?: string | null;
  /**
   * Main photo on the website. Stored in Media.
   */
  featuredImage?: (string | null) | Media;
  /**
   * Extra photos. Stored in Media.
   */
  gallery?: (string | Media)[] | null;
  basePrice: number;
  salePrice?: number | null;
  visitChargeType?: ('default' | 'fixed' | 'area' | 'distance') | null;
  homeVisitCharge?: number | null;
  durationMinutes: number;
  benefits?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  included?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  notIncluded?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  addons?: (string | ServiceAddon)[] | null;
  recommendedServices?: (string | Service)[] | null;
  relatedServices?: (string | Service)[] | null;
  available?: boolean | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-categories".
 */
export interface ServiceCategory {
  id: string;
  name: string;
  slug: string;
  shortDescription?: string | null;
  /**
   * Upload a new file into Media, or choose one already saved there.
   */
  image?: (string | null) | Media;
  active?: boolean | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-addons".
 */
export interface ServiceAddon {
  id: string;
  name: string;
  slug: string;
  description?: string | null;
  price: number;
  durationMinutes?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-areas".
 */
export interface ServiceArea {
  id: string;
  name: string;
  slug: string;
  city: string;
  state: string;
  pincode?: string | null;
  homeVisitCharge: number;
  active?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "time-slots".
 */
export interface TimeSlot {
  id: string;
  label: string;
  /**
   * 24h format, e.g. 09:00
   */
  startTime: string;
  maxBookings: number;
  active?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disabled-dates".
 */
export interface DisabledDate {
  id: string;
  date: string;
  reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beauticians".
 */
export interface Beautician {
  id: string;
  name: string;
  slug: string;
  user?: (string | null) | User;
  /**
   * Photo on the website. Stored in Media.
   */
  profileImage?: (string | null) | Media;
  bio?: string | null;
  experienceYears: number;
  specializations?: (string | ServiceCategory)[] | null;
  services?: (string | Service)[] | null;
  serviceAreas?: (string | ServiceArea)[] | null;
  workingDays?: ('0' | '1' | '2' | '3' | '4' | '5' | '6')[] | null;
  workStart?: string | null;
  workEnd?: string | null;
  available?: boolean | null;
  rating?: number | null;
  totalReviews?: number | null;
  /**
   * Work photos on the profile page. Stored in Media.
   */
  portfolio?: (string | Media)[] | null;
  phone?: string | null;
  whatsapp?: string | null;
  active?: boolean | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: string;
  customer: string | User;
  label: 'home' | 'work' | 'other';
  addressLine: string;
  area: string | ServiceArea;
  city: string;
  state: string;
  pincode: string;
  landmark?: string | null;
  instructions?: string | null;
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments".
 */
export interface Appointment {
  id: string;
  bookingId?: string | null;
  customer?: (string | null) | User;
  customerName: string;
  customerPhone: string;
  customerWhatsapp?: string | null;
  customerEmail?: string | null;
  beautician?: (string | null) | Beautician;
  beauticianUser?: (string | null) | User;
  assignmentMode?: ('auto' | 'manual') | null;
  service: string | Service;
  addons?: (string | ServiceAddon)[] | null;
  appointmentDate: string;
  timeSlot: string | TimeSlot;
  addressSnapshot: string;
  serviceArea: string | ServiceArea;
  pincode?: string | null;
  notes?: string | null;
  serviceAmount: number;
  homeVisitCharge: number;
  addonAmount: number;
  discount: number;
  finalAmount: number;
  coupon?: (string | null) | Coupon;
  couponCode?: string | null;
  paymentMethod?: ('pay-after-service' | 'online' | 'upi' | 'card' | 'net-banking') | null;
  paymentStatus?: ('pending' | 'paid' | 'failed' | 'refunded' | 'partially-paid') | null;
  status:
    | 'pending'
    | 'confirmed'
    | 'assigned'
    | 'on-the-way'
    | 'arrived'
    | 'service-started'
    | 'completed'
    | 'cancelled'
    | 'rescheduled'
    | 'no-show';
  cancellationReason?: string | null;
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: string;
  code: string;
  type: 'percentage' | 'fixed';
  percentage?: number | null;
  fixedAmount?: number | null;
  minimumOrderValue?: number | null;
  maximumDiscount?: number | null;
  usageLimit?: number | null;
  perCustomerLimit?: number | null;
  usedCount?: number | null;
  startDate: string;
  endDate: string;
  applicableServices?: (string | Service)[] | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: string;
  title: string;
  slug: string;
  description?: string | null;
  /**
   * Upload a new file into Media, or choose one already saved there.
   */
  banner?: (string | null) | Media;
  discountLabel?: string | null;
  coupon?: (string | null) | Coupon;
  startDate?: string | null;
  endDate?: string | null;
  services?: (string | Service)[] | null;
  terms?: string | null;
  active?: boolean | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  customer?: (string | null) | User;
  customerName: string;
  /**
   * Upload a new file into Media, or choose one already saved there.
   */
  customerPhoto?: (string | null) | Media;
  service?: (string | null) | Service;
  beautician?: (string | null) | Beautician;
  appointment?: (string | null) | Appointment;
  rating: number;
  review: string;
  verifiedCustomer?: boolean | null;
  published?: boolean | null;
  featured?: boolean | null;
  adminResponse?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "before-after".
 */
export interface BeforeAfter {
  id: string;
  title: string;
  service?: (string | null) | Service;
  beautician?: (string | null) | Beautician;
  /**
   * Upload a new file into Media, or choose one already saved there.
   */
  beforeImage: string | Media;
  /**
   * Upload a new file into Media, or choose one already saved there.
   */
  afterImage: string | Media;
  description?: string | null;
  published?: boolean | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reels".
 */
export interface Reel {
  id: string;
  title: string;
  caption?: string | null;
  /**
   * Cover photo for the reel. Stored in Media.
   */
  thumbnail?: (string | null) | Media;
  /**
   * MP4 or WebM video. Stored in Media.
   */
  video?: (string | null) | Media;
  externalUrl?: string | null;
  service?: (string | null) | Service;
  beautician?: (string | null) | Beautician;
  category?: (string | null) | ServiceCategory;
  published?: boolean | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  question: string;
  answer: string;
  category?: string | null;
  sortOrder?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  excerpt?: string | null;
  /**
   * Upload a new file into Media, or choose one already saved there.
   */
  coverImage?: (string | null) | Media;
  content: string;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string;
  title: string;
  body: string;
  type:
    | 'booking-received'
    | 'booking-confirmed'
    | 'beautician-assigned'
    | 'appointment-reminder'
    | 'appointment-completed'
    | 'review-request'
    | 'admin-new-booking'
    | 'cancellation'
    | 'new-review'
    | 'new-customer';
  audience: 'customer' | 'admin' | 'beautician';
  user?: (string | null) | User;
  appointment?: (string | null) | Appointment;
  read?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'service-categories';
        value: string | ServiceCategory;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'service-addons';
        value: string | ServiceAddon;
      } | null)
    | ({
        relationTo: 'service-areas';
        value: string | ServiceArea;
      } | null)
    | ({
        relationTo: 'time-slots';
        value: string | TimeSlot;
      } | null)
    | ({
        relationTo: 'disabled-dates';
        value: string | DisabledDate;
      } | null)
    | ({
        relationTo: 'beauticians';
        value: string | Beautician;
      } | null)
    | ({
        relationTo: 'addresses';
        value: string | Address;
      } | null)
    | ({
        relationTo: 'appointments';
        value: string | Appointment;
      } | null)
    | ({
        relationTo: 'coupons';
        value: string | Coupon;
      } | null)
    | ({
        relationTo: 'offers';
        value: string | Offer;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'before-after';
        value: string | BeforeAfter;
      } | null)
    | ({
        relationTo: 'reels';
        value: string | Reel;
      } | null)
    | ({
        relationTo: 'faqs';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'notifications';
        value: string | Notification;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  phone?: T;
  whatsapp?: T;
  photo?: T;
  accountStatus?: T;
  favouriteServices?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  folder?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-categories_select".
 */
export interface ServiceCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortDescription?: T;
  image?: T;
  active?: T;
  featured?: T;
  sortOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  shortDescription?: T;
  fullDescription?: T;
  featuredImage?: T;
  gallery?: T;
  basePrice?: T;
  salePrice?: T;
  visitChargeType?: T;
  homeVisitCharge?: T;
  durationMinutes?: T;
  benefits?:
    | T
    | {
        item?: T;
        id?: T;
      };
  included?:
    | T
    | {
        item?: T;
        id?: T;
      };
  notIncluded?:
    | T
    | {
        item?: T;
        id?: T;
      };
  addons?: T;
  recommendedServices?: T;
  relatedServices?: T;
  available?: T;
  featured?: T;
  sortOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-addons_select".
 */
export interface ServiceAddonsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  price?: T;
  durationMinutes?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-areas_select".
 */
export interface ServiceAreasSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  city?: T;
  state?: T;
  pincode?: T;
  homeVisitCharge?: T;
  active?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "time-slots_select".
 */
export interface TimeSlotsSelect<T extends boolean = true> {
  label?: T;
  startTime?: T;
  maxBookings?: T;
  active?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disabled-dates_select".
 */
export interface DisabledDatesSelect<T extends boolean = true> {
  date?: T;
  reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beauticians_select".
 */
export interface BeauticiansSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  user?: T;
  profileImage?: T;
  bio?: T;
  experienceYears?: T;
  specializations?: T;
  services?: T;
  serviceAreas?: T;
  workingDays?: T;
  workStart?: T;
  workEnd?: T;
  available?: T;
  rating?: T;
  totalReviews?: T;
  portfolio?: T;
  phone?: T;
  whatsapp?: T;
  active?: T;
  featured?: T;
  sortOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customer?: T;
  label?: T;
  addressLine?: T;
  area?: T;
  city?: T;
  state?: T;
  pincode?: T;
  landmark?: T;
  instructions?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments_select".
 */
export interface AppointmentsSelect<T extends boolean = true> {
  bookingId?: T;
  customer?: T;
  customerName?: T;
  customerPhone?: T;
  customerWhatsapp?: T;
  customerEmail?: T;
  beautician?: T;
  beauticianUser?: T;
  assignmentMode?: T;
  service?: T;
  addons?: T;
  appointmentDate?: T;
  timeSlot?: T;
  addressSnapshot?: T;
  serviceArea?: T;
  pincode?: T;
  notes?: T;
  serviceAmount?: T;
  homeVisitCharge?: T;
  addonAmount?: T;
  discount?: T;
  finalAmount?: T;
  coupon?: T;
  couponCode?: T;
  paymentMethod?: T;
  paymentStatus?: T;
  status?: T;
  cancellationReason?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  type?: T;
  percentage?: T;
  fixedAmount?: T;
  minimumOrderValue?: T;
  maximumDiscount?: T;
  usageLimit?: T;
  perCustomerLimit?: T;
  usedCount?: T;
  startDate?: T;
  endDate?: T;
  applicableServices?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  banner?: T;
  discountLabel?: T;
  coupon?: T;
  startDate?: T;
  endDate?: T;
  services?: T;
  terms?: T;
  active?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  customer?: T;
  customerName?: T;
  customerPhoto?: T;
  service?: T;
  beautician?: T;
  appointment?: T;
  rating?: T;
  review?: T;
  verifiedCustomer?: T;
  published?: T;
  featured?: T;
  adminResponse?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "before-after_select".
 */
export interface BeforeAfterSelect<T extends boolean = true> {
  title?: T;
  service?: T;
  beautician?: T;
  beforeImage?: T;
  afterImage?: T;
  description?: T;
  published?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reels_select".
 */
export interface ReelsSelect<T extends boolean = true> {
  title?: T;
  caption?: T;
  thumbnail?: T;
  video?: T;
  externalUrl?: T;
  service?: T;
  beautician?: T;
  category?: T;
  published?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  sortOrder?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  type?: T;
  audience?: T;
  user?: T;
  appointment?: T;
  read?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  businessName: string;
  tagline?: string | null;
  /**
   * Upload a new file into Media, or choose one already saved there.
   */
  logo?: (string | null) | Media;
  /**
   * Upload a new file into Media, or choose one already saved there.
   */
  favicon?: (string | null) | Media;
  headerLinks?:
    | {
        label: string;
        /**
         * Page path, e.g. /services
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  headerCtaLabel?: string | null;
  headerCtaHref?: string | null;
  footerTagline?: string | null;
  footerExploreLinks?:
    | {
        label: string;
        /**
         * Page path, e.g. /services
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  footerPolicyLinks?:
    | {
        label: string;
        /**
         * Page path, e.g. /services
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  phone: string;
  whatsapp: string;
  email: string;
  address?: string | null;
  instagram?: string | null;
  facebook?: string | null;
  businessHours?: string | null;
  defaultHomeVisitCharge: number;
  currency?: string | null;
  minAdvanceDays?: number | null;
  maxAdvanceDays?: number | null;
  cancellationHours?: number | null;
  mobileBookLabel?: string | null;
  seo?: {
    defaultTitle?: string | null;
    defaultDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: string;
  heroBadge?: string | null;
  heroHeadline?: string | null;
  heroText?: string | null;
  /**
   * Large photo on the home page. Stored in Media.
   */
  heroImage?: (string | null) | Media;
  primaryCtaLabel?: string | null;
  primaryCtaHref?: string | null;
  secondaryCtaLabel?: string | null;
  secondaryCtaHref?: string | null;
  servicesTitle?: string | null;
  howItWorksTitle?: string | null;
  howItWorks?:
    | {
        title: string;
        id?: string | null;
      }[]
    | null;
  whyTitle?: string | null;
  whyItems?:
    | {
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  beforeAfterTitle?: string | null;
  beauticiansTitle?: string | null;
  reelsTitle?: string | null;
  reviewsTitle?: string | null;
  offersTitle?: string | null;
  faqTitle?: string | null;
  finalCtaHeadline?: string | null;
  finalCtaText?: string | null;
  finalCtaLabel?: string | null;
  finalCtaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  businessName?: T;
  tagline?: T;
  logo?: T;
  favicon?: T;
  headerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  headerCtaLabel?: T;
  headerCtaHref?: T;
  footerTagline?: T;
  footerExploreLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerPolicyLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  copyrightText?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  address?: T;
  instagram?: T;
  facebook?: T;
  businessHours?: T;
  defaultHomeVisitCharge?: T;
  currency?: T;
  minAdvanceDays?: T;
  maxAdvanceDays?: T;
  cancellationHours?: T;
  mobileBookLabel?: T;
  seo?:
    | T
    | {
        defaultTitle?: T;
        defaultDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroBadge?: T;
  heroHeadline?: T;
  heroText?: T;
  heroImage?: T;
  primaryCtaLabel?: T;
  primaryCtaHref?: T;
  secondaryCtaLabel?: T;
  secondaryCtaHref?: T;
  servicesTitle?: T;
  howItWorksTitle?: T;
  howItWorks?:
    | T
    | {
        title?: T;
        id?: T;
      };
  whyTitle?: T;
  whyItems?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  beforeAfterTitle?: T;
  beauticiansTitle?: T;
  reelsTitle?: T;
  reviewsTitle?: T;
  offersTitle?: T;
  faqTitle?: T;
  finalCtaHeadline?: T;
  finalCtaText?: T;
  finalCtaLabel?: T;
  finalCtaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}